import os

from dotenv import load_dotenv

load_dotenv()

justEatPayload = {
    "location": "",
    "account": "",
    "posSystemId": 10123,
    "taxExcl": False,
    "timezone": "Europe/London",
    "fulfillmentEnabled": False,
    "channelSettings":
    {
        "channelAppendsDiscountedItems": True,
        "needsChannelValidation": True,
        "useNewPromotions": False,
        "useUpdateOrderItemsFlow": False,
        "insertPosOrderAfterDmaAccept": False,
        "addManagementFee": False,
        "autoAcceptOrderStatus": 20,
        "sendToQuest": True,
        "useChannelItemNames": False,
        "logChannelOperations": True,
        "sendRejectStatus": False,
        "sendUnitPricing": True,
        "supportsUnlimitedMenus": False,
        "useServiceTimes": False,
        "sendProductTypesInMenuPush": False,
        "sendUniqueReferences": False,
        "sendQuantityRestrictions": True,
        "usePortions": False,
        "sendNutritionalInfoAsAdditionalDetails": False,
        "sendCaloriesAsKJ": False,
        "inventoryPushWindow": 600,
        "snoozeBatchWindow": 300,
        "coreFlatten": False,
        "sendDepositsForEatIn": False,
        "isSnoozeRestricted": False,
        "isMenuPushRestricted": False,
        "brandSlug": "",
        "alcoholMenuEnabled": False,
        "APIkey": os.getenv("JUST_EAT_API_KEY", ""),
        "application": "PRODUCTION",
        "locReference": "",
        "restaurantId": ""
    },
    "posSettings":
    {
        "generic":
        {
            "locationId": "",
            "ordersWebhookURL": "",
            "syncTablesURL": "",
            "syncFloorsURL": "",
            "syncBillsURL": "",
            "billPaymentURL": "",
            "operationsWebhookURL": "",
            "storeStatusWebhookURL": "",
            "productPushWebhookURL": "",
            "taxCalculationWebhookURL": "",
            "customHeaders": "",
            "syncProductsURL": "",
            "productSyncType": 1,
            "defaultDeliveryTax": "",
            "defaultTakeawayTax": "",
            "defaultEatInTax": "",
            "anonymizeCustomer": False,
            "doNotSendTaxRemit": False,
            "sendStreetNumber": False,
            "ignoreUnknownDiscounts": False,
            "hasDirectTableIntegration": False,
            "sendDiscount": False,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "sendDeliveryFeeCondition": 0,
            "forcePayment": 0,
            "sortModifiers": 0,
            "bufferOrders": False,
            "separateSameProducts": False,
            "dontSendCancel": False,
            "supportsTaxExclusiveCalculation": False,
            "deliveryByChannelIsPickup": False,
            "autoAcceptRetailOrder": False,
            "allowSubstitutionBypass": False,
            "orderNoteTemplate": "",
            "readonly": False,
            "logOps": True,
            "isGenericPickingActive": False,
            "genericPickingApiKey": "",
            "orderWebhookUrl": "",
            "orderUpdatesUrl": "",
            "getSubstitutesUrl": "",
            "orderItemRemarks": "intactItemRemarks",
            "alwaysSendAllSnoozedProducts": True,
            "setDefaultPriceLevelOnSync": False,
            "sendTip": False,
            "sendRebate": False,
            "ignoreUnknownOrderStatuses": False,
            "recalcPriceOverrides": False,
            "averagePreparationTime": 6,
            "bottleDepositPLU": "",
            "averageDeliveryTime": 15,
            "enforceScanning": False
        }
    },
    "paymentProfile": "",
    "menuUrl": "",
    "status": 3,
    "name": "Just Eat",
    "channel": 6009,
    "priceLevelSettings":
    {},
    "anonymizeCustomer": False,
    "bufferOrders": False,
    "defaultPreparationTime": 6,
    "averageDeliveryTime": 15,
    "mockPOS": False,
    "logPOS": True,
    "APIKey": "",
    "application": "PRODUCTION"
}



deliverooPayload = {
    "location": "",
    "account": "",
    "posSystemId": 10123,
    "taxExcl": False,
    "timezone": "Europe/London",
    "fulfillmentEnabled": False,
    "channelSettings":
    {
        "enableForceRelease": False,
        "isUpdateFlowSynchronous": False,
        "insertPosOrderAfterDmaAccept": False,
        "useChannelPrepTime": True,
        "sendToQuest": False,
        "useChannelItemNames": False,
        "logChannelOperations": False,
        "sendRejectStatus": False,
        "validateBusyMode": False,
        "useCategoriesExperience": False,
        "syncItemAvailabilities": True,
        "applyPriceLevels": False,
        "updateOpeningHours": True,
        "skipHeaderImageResizer": False,
        "setItemMaxQuantity": False,
        "skipItemImageResizer": False,
        "sendCaloriesAsKJ": False,
        "inventoryPushWindow": 600,
        "snoozeBatchWindow": 300,
        "coreFlatten": False,
        "sendDepositsForEatIn": False,
        "isSnoozeRestricted": False,
        "isMenuPushRestricted": False,
        "defaultTaxRate": 10,
        "catalogPushEnabled": True,
        "useOAuth": True,
        "application": "PRODUCTION",
        "brandId": "one-stop-stores-ltd-deliverect-retail-new-gb",
        "countryCode": "GB"
    },
    "posSettings":
    {
        "generic":
        {
            "locationId": "",
            "ordersWebhookURL": "",
            "syncTablesURL": "",
            "syncFloorsURL": "",
            "syncBillsURL": "",
            "billPaymentURL": "",
            "operationsWebhookURL": "",
            "storeStatusWebhookURL": "",
            "productPushWebhookURL": "",
            "taxCalculationWebhookURL": "",
            "customHeaders": "",
            "syncProductsURL": "",
            "productSyncType": 1,
            "defaultDeliveryTax": "",
            "defaultTakeawayTax": "",
            "defaultEatInTax": "",
            "anonymizeCustomer": False,
            "doNotSendTaxRemit": False,
            "sendStreetNumber": False,
            "ignoreUnknownDiscounts": False,
            "hasDirectTableIntegration": False,
            "sendDiscount": False,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "sendDeliveryFeeCondition": 0,
            "forcePayment": 0,
            "sortModifiers": 0,
            "bufferOrders": False,
            "separateSameProducts": False,
            "dontSendCancel": False,
            "supportsTaxExclusiveCalculation": False,
            "deliveryByChannelIsPickup": False,
            "autoAcceptRetailOrder": False,
            "allowSubstitutionBypass": False,
            "orderNoteTemplate": "",
            "readonly": False,
            "logOps": True,
            "isGenericPickingActive": False,
            "genericPickingApiKey": "",
            "orderWebhookUrl": "",
            "orderUpdatesUrl": "",
            "getSubstitutesUrl": "",
            "orderItemRemarks": "intactItemRemarks",
            "alwaysSendAllSnoozedProducts": True,
            "setDefaultPriceLevelOnSync": False,
            "sendTip": False,
            "sendRebate": False,
            "ignoreUnknownOrderStatuses": False,
            "recalcPriceOverrides": False,
            "averagePreparationTime": 6,
            "bottleDepositPLU": "",
            "averageDeliveryTime": 15,
            "enforceScanning": False
        }
    },
    "paymentProfile": "",
    "menuUrl": "",
    "status": 3,
    "name": "Deliveroo",
    "channel": 6002,
    "priceLevelSettings":
    {},
    "anonymizeCustomer": False,
    "bufferOrders": False,
    "defaultPreparationTime": 6,
    "averageDeliveryTime": 15,
    "mockPOS": False,
    "logPOS": True,
    "application": "PRODUCTION"
}


uberEatsPayload = {
    "location": "",
    "account": "",
    "posSystemId": 10123,
    "taxExcl": False,
    "timezone": "Europe/London",
    "fulfillmentEnabled": False,
    "channelSettings":
    {
        "asyncSnooze": True,
        "removeDeliveryDiscount": False,
        "scheduleOrderWebhooks": False,
        "sendTotalFeeAsServiceCharge": False,
        "useUpdateOrderItemsFlow": False,
        "releaseOrderAfterPickUp": False,
        "enableReleaseCall": False,
        "pollPickupTime": False,
        "insertPosOrderAfterDmaAccept": False,
        "autoAcceptOrderStatus": 20,
        "sendSharedChannelAndRestaurantDiscounts": False,
        "autoReenableOrderManager": True,
        "orderNoteTemplate": "",
        "excludeContactInfo": False,
        "sendReceiptId": False,
        "useNewOrderAPI": True,
        "sendToQuest": False,
        "useChannelItemNames": False,
        "logChannelOperations": True,
        "sendRejectStatus": False,
        "allowRequestingMultipleCouriers": False,
        "clearZeroTaxRates": False,
        "resizeImagesToFitDimensions": False,
        "sendDepositSeparately": False,
        "splitMenuTypes": False,
        "includeLegalNameInProductDescription": False,
        "skipImageResizer": False,
        "sendEnergyInfoAs": "Cal",
        "enableItemLevelNotes": False,
        "checkRemoteSnoozes": False,
        "validateMenu": False,
        "inventoryPushWindow": 600,
        "snoozeBatchWindow": 300,
        "coreFlatten": False,
        "sendDepositsForEatIn": False,
        "isSnoozeRestricted": False,
        "isMenuPushRestricted": False,
        "storeId": "",
        "defaultTaxRate": 10,
        "catalogSFTPDirectoryName": "Onestop",
        "catalogSFTPPushProd": True,
        "catalogSFTPConnectionConfigKey": "uber_eats_uk",
        "catalogPushEnabled": True,
        "application": "RETAIL_FLOOID",
        "provisioning": 0
    },
    "posSettings":
    {
        "generic":
        {
            "locationId": "",
            "ordersWebhookURL": "",
            "syncTablesURL": "",
            "syncFloorsURL": "",
            "syncBillsURL": "",
            "billPaymentURL": "",
            "operationsWebhookURL": "",
            "storeStatusWebhookURL": "",
            "productPushWebhookURL": "",
            "taxCalculationWebhookURL": "",
            "customHeaders": "",
            "syncProductsURL": "",
            "productSyncType": 1,
            "defaultDeliveryTax": "",
            "defaultTakeawayTax": "",
            "defaultEatInTax": "",
            "anonymizeCustomer": False,
            "doNotSendTaxRemit": False,
            "sendStreetNumber": False,
            "ignoreUnknownDiscounts": False,
            "hasDirectTableIntegration": False,
            "sendDiscount": False,
            "sendDeliveryFee": False,
            "sendServiceCharge": False,
            "sendDeliveryFeeCondition": 0,
            "forcePayment": 0,
            "sortModifiers": 0,
            "bufferOrders": False,
            "separateSameProducts": False,
            "dontSendCancel": False,
            "supportsTaxExclusiveCalculation": False,
            "deliveryByChannelIsPickup": False,
            "autoAcceptRetailOrder": True,
            "allowSubstitutionBypass": False,
            "orderNoteTemplate": "",
            "readonly": False,
            "logOps": True,
            "isGenericPickingActive": False,
            "genericPickingApiKey": "",
            "orderWebhookUrl": "",
            "orderUpdatesUrl": "",
            "getSubstitutesUrl": "",
            "orderItemRemarks": "intactItemRemarks",
            "alwaysSendAllSnoozedProducts": True,
            "setDefaultPriceLevelOnSync": False,
            "sendTip": False,
            "sendRebate": False,
            "ignoreUnknownOrderStatuses": False,
            "recalcPriceOverrides": False,
            "averagePreparationTime": 6,
            "bottleDepositPLU": "",
            "averageDeliveryTime": 15,
            "enforceScanning": False
        }
    },
    "paymentProfile": "",
    "menuUrl": "",
    "status": 3,
    "name": "Uber Eats",
    "channel": 6007,
    "priceLevelSettings":
    {},
    "anonymizeCustomer": False,
    "bufferOrders": False,
    "defaultPreparationTime": 6,
    "averageDeliveryTime": 15,
    "mockPOS": False,
    "logPOS": True,
    "application": "RETAIL_FLOOID",
    "APIKey": ""
}

